// Register
export const REGISTER_REQUEST = "users/REGISTER_REQUEST";
export const REGISTER_REQUEST_FAILURE = "users/REGISTER_REQUEST_FAILURE";
export const REGISTER_SUCCESS_RESPONSE = "users/REGISTER_SUCCESS_RESPONSE";