// Get All Users Chat
export const GET_ALL_USERS_CHAT_REQUEST = "chats/GET_ALL_USERS_CHAT_REQUEST";
export const GET_ALL_USERS_CHAT_REQUEST_FAILURE = "chats/GET_ALL_USERS_CHAT_REQUEST_FAILURE";
export const GET_ALL_USERS_CHAT_SUCCESS_RESPONSE = "chats/GET_ALL_USERS_CHAT_SUCCESS_RESPONSE";

// Get All Users
export const GET_ALL_USERS_REQUEST = "users/GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_REQUEST_FAILURE = "users/GET_ALL_USERS_REQUEST_FAILURE";
export const GET_ALL_USERS_SUCCESS_RESPONSE = "users/GET_ALL_USERS_SUCCESS_RESPONSE";

// Add New Chat
export const ADD_NEW_CHAT_REQUEST = "chats/ADD_NEW_CHAT_REQUEST";
export const ADD_NEW_CHAT_REQUEST_FAILURE = "chats/ADD_NEW_CHAT_REQUEST_FAILURE";
export const ADD_NEW_CHAT_SUCCESS_RESPONSE = "chats/ADD_NEW_CHAT_SUCCESS_RESPONSE";

// Get all messages
export const GET_MESSAGES_REQUEST = "messages/GET_MESSAGES_REQUEST";
export const GET_MESSAGES_REQUEST_FAILURE = "messages/GET_MESSAGES_REQUEST_FAILURE";
export const GET_MESSAGES_SUCCESS_RESPONSE = "messages/GET_MESSAGES_SUCCESS_RESPONSE";

// Send messages
export const SEND_MESSAGES_REQUEST = "messages/SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_REQUEST_FAILURE = "messages/SEND_MESSAGES_REQUEST_FAILURE";
export const SEND_MESSAGES_SUCCESS_RESPONSE = "messages/SEND_MESSAGES_SUCCESS_RESPONSE";